messages:
    terrain:
        created: "&fSe ha creado el terreno &a%id% &fcorrectamente"
        deleted: "&fEl terreno &a%id% &fTerreno eliminado correctamente"
        teleported: "&fHas sido llevado al terreno &a%id%"
        moved-origin: "&fSe ha movido la posici칩n de origen del terreno &a%id% &fcorrectamente"
        no-target-block: "&fDebes estar mirando un bloque para poder hacer esto"
        target-not-sign: "&fDebes mirar una se침al para poder hacer esto"
        set-sign-location: "&fSe ha establecido la localizaci칩n del cartel para el terreno &a%id%"
        set-skull-location: "&fSe ha establecido la localizaci칩n de la cabeza para el terreno &a%id%"
        set-cuboid: "&fSe ha establecido el cubo para el terreno &a%id%"
        no-selection: "&fDebes seleccionar un cubo para poder hacer esto"