schematic:
    path: "/home/pixeldev/05_Survival_Pk/schematics"

messages:
    user:
        already-claimed-terrain: "&fYa tienes reclamado un terreno, no puedes reclamar otro"
        no-claim-permission: "&fNo tienes permiso para reclamar terrenos"
    terrain:
        created: "&fSe ha creado el terreno &a%id% &fcorrectamente"
        deleted: "&fEl terreno &a%id% &fTerreno eliminado correctamente"

        teleported: "&fHas sido llevado al terreno &a%id%"
        moved-origin: "&fSe ha movido la posición de origen del terreno &a%id% &fcorrectamente"

        claimed: "&fHas reclamado este terreno correctamente, recuerda que construir cosas obsenas te hará perder este privilegio."
        already-claimed-by-other: "&fEse terreno está ocupado por otro jugador"
        already-claimed-by-you: "&fEste terreno ya está ocupado por ti"

        no-target-block: "&fDebes estar mirando un bloque para poder hacer esto"
        no-sign-block: "&fDebes mirar una señal para poder hacer esto"
        set-sign-location: "&fSe ha establecido la localización del cartel para el terreno &a%id%"
        set-skull-location: "&fSe ha establecido la localización de la cabeza para el terreno &a%id%"
        no-skull-block: "&fDebes mirar una cabeza de jugador para poder hacer esto"

        set-cuboid: "&fSe ha establecido el cubo para el terreno &a%id%"
        no-selection: "&fDebes seleccionar un cubo para poder hacer esto"

        setup-completed: "&fSe ha completado la configuración del terreno &a%id%"
        missing-sign: "&a - &fEstablecer la localización del cartel para el terreno."
        missing-skull: "&a - &fEstablecer la localización de la cabeza para el terreno."
        missing-cuboid: "&a - &fEstablecer el cubo para el terreno."
        missing-setup:
            - "&a-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
            - "&fAún faltan configuraciones para el terreno &a%id%&f:"
            - " "
            - "%missing%"
            - "&a-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"