name: TerrainHousing
main: net.cosmogrp.thousing.TerrainHousingPlugin
version: @version@
author: CosmoGroup Development
api-version: 1.13
description: Build you beautiful house in a designated area, access everywhere!
